import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
export default function Home() {
  const [url, setUrl] = useState("");
  const [json, setJson] = useState({});

  const test = async () => {
    const response = await fetch(url);
    const json = await response.json()
    console.log(json);
    setJson(json);
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input value={url} onChange={(e) => setUrl(e.target.value)}></input>
        <button onClick={test}>Click</button>
        <div>{JSON.stringify(json)}</div>
      </main>
    </div>
  )
}
